# Generated by Django 4.0.4 on 2022-06-07 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound_name', models.CharField(max_length=50)),
                ('sound_path', models.CharField(max_length=100)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GSA.instrument')),
            ],
        ),
    ]
