# Generated by Django 4.0.4 on 2022-06-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GSA', '0002_instrument_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='sound_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
